- .golangci.yml
- tests/e2e/README.md
> Chore: remove references to Gitlab

- .env-sample.yaml
> chore(env): add .env-sample.yaml

- api/grpc/security_interceptors.go
- api/grpc/server.go
- api/rest/panic_handler.go
- api/rest/route_groups.go
- api/rest/route_groups_test.go
- api/rest/route_user.go
- api/rest/route_user_test.go
- api/rest/router.go
- api/rest/security_middleware.go
- api/rest/security_middleware_test.go
- cmd/main.go
- go.mod
- security/validate_token.go
- services/okta/client.go
- services/okta/controller.go
- services/okta/group_memberships.go
- services/okta/group_memberships_test.go
- services/okta/groups.go
- services/okta/http.go
- services/okta/http_test.go
- services/okta/teams.go
> Chore: update IAM imports

- .circleci/config.yml
- Dockerfile
> Docker: make .well-known and .env.yaml optional

- www/publish.sh
And only push to gh-pages, not all branches.
> CI: do not fail docs/publish if there are no changes

- README.md
Add some explanation on how to set your paths in Go (`GOPATH` and `PATH` updates for it to find the binaries), for those new to it (like me 😃  ), who are faced with the issue of Golang not finding some packages.
> update(README): Updated readme with path setting issue in Golang

- .circleci/config.yml
- commitsar validates commit message compliance
> chore: add commitsar

- .circleci/config.yml
Commitsar was updated to new namespace and a bug has been fixed to do with Github merges.
> fix: update commitsar

- .circleci/config.yml
- www/docs.mk
- www/go.sum
- www/publish.sh
- runs publish with sh
- updates go.sum
> fix: deployment of pages

- .circleci/config.yml
- also removes redundant fields
> chore: pin Hugo image version

- api/grpc/server.go
- cmd/main.go
- configs/environment.go
> GRPC: load TLS certificates from path

- .circleci/config.yml
- .github/workflows/commitsar.yml
- adds latest Commitsar Github action
- removes Commitsar from CircleCI
> chore(ci): add Commitsar Github Action

- renovate.json
- we are not using any of the special features
> chore: simplify renovate

- api/grpc/security_interceptors.go
- api/grpc/server.go
- api/rest/panic_handler.go
- api/rest/route_groups.go
- api/rest/route_groups_test.go
- api/rest/route_user.go
- api/rest/route_user_test.go
- api/rest/router.go
- api/rest/security_middleware.go
- api/rest/security_middleware_test.go
- cmd/main.go
- go.mod
- internal/security/validate_token.go
- internal/services/okta/client.go
- internal/services/okta/controller.go
- internal/services/okta/group_memberships.go
- internal/services/okta/group_memberships_test.go
- internal/services/okta/groups.go
- internal/services/okta/http.go
- internal/services/okta/http_test.go
- internal/services/okta/teams.go
> fix: go mod uses wrong address

- Makefile
- internal/services/okta/permissions.go
- internal/services/okta/permissions_test.go
First step for #121 
I will add the extra route and the e2e tests as a separate PR.
> Okta: retrieve permissions for services

- .github/workflows/release.yml
- automatically publishes release notes to new tags
> chore(ci): add Release Note publishing

- api/rest/route_permissions.go
- api/rest/route_permissions_test.go
- api/rest/route_user_test.go
- api/rest/router.go
- tests/e2e/nginx/mocks/groups/index.json
- tests/e2e/venom/http_client_test.yml
Adds route and tests for #132 
References #121
> feat(okta): add services permissions route

- cmd/main.go
- internal/storage/redis_cache.go
- internal/storage/redis_cache_test.go
- adds version to cache keys which allows for forwards compatible changes
- sets version to 1
References #152
> feat(redis): cache versioning

- internal/storage/redis_cache.go
- NewRedisCache was not propagating version argument
> fix(cache): version is now applied correctly

- go.mod
- go.sum
- internal/services/okta/client.go
- internal/services/okta/controller.go
- internal/services/okta/http.go
Fix usage of our Datadog metrics and update dependencies.
> Fix usage of metric tags
